config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get "following"
        get "followers"
      end
    end
    resources :users, only: [:index, :new, :create, :show, :destroy]
    resources :microposts, only: [:create, :destroy]
    resources :relationships, only: [:create, :destroy]
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t "static_pages.footer.content_html" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("static_pages.about.title"), "#" %></li>
      <li><%= link_to t("static_pages.contact.title"), "#" %></li>
      <li><%= link_to t("static_pages.footer.title_link"), t("static_pages.footer.link") %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
  <%= link_to "sample app", "#", id: "logo" %>
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to t("static_pages.home.title"), root_path %></li>
      <li><%= link_to t("static_pages.help.title"), help_path %></li>
      <li><%= link_to t("static_pages.lang.en"), locale:"en" %></li>
      <li><%= link_to t("static_pages.lang.vi"), locale:"vi" %></li>
      <% if logged_in? %>
          <li><%= link_to t("static_pages.users.current.user"), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t("static_pages.users.current.account") %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("static_pages.users.new.profile"), current_user %></li>
              <li><%= link_to t("static_pages.users.new.setting"), new_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("static_pages.users.new.log_out"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("static_pages.users.new.log_in"), login_path %></li>
        <% end %>
      </ul>
  </nav>
</div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/_slim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/slim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>